<link rel="stylesheet" type="text/css" href="${ctx}/static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="${ctx}/static/css/master.css">
<link rel="stylesheet" type="text/css" href="${ctx}/static/css/index.css">
<link rel="stylesheet" type="text/css" href="${ctx}/static/css/model.css">
<link rel="stylesheet" type="text/css" href="${ctx}/static/css/my.css">

<script language="javascript" src="${ctx}/static/js/html5shiv.js"></script>
<script language="javascript" src="${ctx}/static/js/respond.min.js"></script>
<script language="javascript" src="${ctx}/static/js/jquery-1.11.1.min.js"></script>
<script language="javascript" src="${ctx}/static/js/bootstrap.min.js"></script>

<link rel="icon" href="${ctx}/static/images/favicon.ico" type="image/x-icon"/>

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">